import React from 'react'
import BooksTable from '../BooksTable/BooksTable'
import { Link } from 'react-router-dom'

export const Books = () => {
    return (
        <main>
            <Link to="/livros/inserirlivro">Inserir Livro</Link>
            <Link to="/livros/alterarlivro">Alterar Livro</Link>
            <Link to="/livros/deletarlivro">Deletar Livro</Link>
            <BooksTable />
        </main>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    )
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   